### ISSUE TITLE
First Issue! - core_example.py import fail

### ISSUE THREAD

**Issue by Cyberface** [llondon6/nrutils_dev#1]
Cyberface has tried to run core_example.py on his mac and as encountered an error

```
Sebastians-MacBook-Pro-2:examples sebastian$ python core_example.py
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

>> Initiating nrutils.
>> Please note style conventions:
   * lower case function/method/variable names
   * no underscore in names unless there are repeated letters
   * information is implicitely in time domain unless explicitely stated.
   * frequency domain information will start with "fd".

nrutils:

  .:
Traceback (most recent call last):
  File "core_example.py", line 11, in <module>
    from nrutils.core.nrsc import *
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nrutils/__init__.py", line 68, in <module>
    exec 'import %s' % p
  File "<string>", line 1
    import
          ^
SyntaxError: invalid syntax
```

**Comment by llondon6** [comment]
Hi Cyberface! Thanks a bunch for trying to run core_example.py

How did you install the package? (How did you make nrutils visible to your python path?)

**Comment by Cyberface** [comment]
I ran

```
Python setup.py install 
```

Shouldn't that do you pythonpath for you?

**Comment by llondon6** [comment]
Indeed, it does. I will look into this further, but for now, I have verified that the following steps allow you to import the package:

* install numpy, ipython, h5py, matplotlib and scipy
* clone nrutils_dev
* manually add this directory to your python path, and you should *almost* be good to go
* you will need to modify per your configuration bam.template (copy to bam.ini), sxs.template (copy to sxs.ini), and template_paths.ini (copy to paths.ini)

I need to learn more about integrating packages with setup.py files. Note that there is also an apparent issue with the matplotlib backend if the above steps are performed in a virtual environment. :-(

**Comment by llondon6** [comment]
Hmm, it looks like a more involved setup file is needed: the current file only copies the init file to the user's python path upon ` setup.py install`

**Comment by Cyberface** [comment]
Ok cool looks like MANIFEST.in did the job!
Now I'm trying to get scsearch() to find waveforms.
It finds zero right now!

A thought... the SXS data in .asc should be placed on MINION or HOGSHEAD somewhere where we can update it with the latest waveforms and where we can all access it

**Comment by llondon6** [comment]
Good idea. I have started the sxsdltool running to dump data to: `/mnt/hogshead/NR_data/SXS`. I will check the permissions when it's done.

**Comment by Cyberface** [comment]
Awesome!

I have made my first pull request! Just a quick test really.
I can't seem to assign anyone it though? Can you change the permissions for myself and @Galadirith or something so we can assign PRs?

**Comment by Cyberface** [comment]
actually I don't think ```MANIFEST.in``` did the job ahah

**Comment by Cyberface** [comment]
Ok I will close this

The current fix is to add the path the ```nrutils_dev``` to your PYTHONPATH
