### ISSUE TITLE
virtual environments, paths.ini and scbuild

### ISSUE THREAD

**Issue by llondon6** [llondon6/nrutils_dev#16]
Seb, Ed, would either of you mind adding a description of "pip install -e ..." to the readme?

**Comment by Galadirith** [comment]
Hi Lionel ,no problem :D I'll do that now.

**Comment by Galadirith** [comment]
Hey Lionel all done at 4292c51f4050fe00fffb75e842aa6eae4d979f98, hopefully that makes sense. Let me know if it doesn't :D

**Comment by llondon6** [comment]
thanks a bunch, Ed!
