### ISSUE TITLE
I would like to be able to specify which SXS waveform to use based on their Lev number

### ISSUE THREAD

**Issue by Cyberface** [llondon6/nrutils_dev#17]

**Comment by llondon6** [comment]
Do you mean extrapolation order?

Try this:

'''
from nrutils.core.nrsc import *
A = scsearch(keyword='sxs0001',verbose=True)
y = gwylm(A[0],lm=[2,2],extraction_parameter=2)
'''

**Comment by Cyberface** [comment]
No instead I mean the different resolutions for a particular system. So for example many SXS datasets were performed at 3 different resolutions of levels "Lev". Currently we only download the highest Lev but we should download all the Levs and be able to choose which one and also which extrapolation order.

**Comment by llondon6** [comment]
I see. This is an issue for the sxsdltool. I'll take a look.

**Comment by Cyberface** [comment]
Thanks!

**Comment by llondon6** [comment]
I've taken a quick look at this, and recall why it's not already
implemented. Not all simulations have the same number of Levs.

It is relatively easy to add an option to the sxsdltool to try and download
a single specified level, and not encounter a fatal error if the level does
not exist.

It's less trivial to have the tool automatically download all available
levels.

Which are you asking for?

**Comment by Cyberface** [comment]
I would be asking for the latter and less trivial one. To download all available Levs.... I'm happy to work on the code with you (even though I am terrible I don't want to pile work on you of course!!)

**Comment by llondon6** [comment]
Hmm, I think that the current may be flexible enough to allow for the
automated downloading of all Levs with an added additional for-loop. I'll
give this a try. Hopefully it's not too bothersome to get right.

**Comment by Cyberface** [comment]
OK cool! Let me know if i can do anything

**Comment by llondon6** [comment]
I'll have to take another look at this once I've updated my SXS catalog; code related to how nrutils handles sxs data will possibly change
