### ISSUE TITLE
calculation of location of max amp via argmax needs to be improved

### ISSUE THREAD

**Issue by Cyberface** [llondon6/nrutils_dev#18]
For some of the higher modes the current method of shifting the time series by the peak amplitude doesn't work and is indeed wrong I think when dealing with multiple modes.

Currently in the gwf class the time domain data is shifted by the location of the peak amplitude to line it up at zero.

This doesn't work when the junk radiation is larger that the peak at merger **and** I think this is actually the wrong way to treat this problem. The time delay between the peaks of different modes should be preserved and so we should shift them by the time-shift applied to the 22 mode.

We will have to think how to incorporate this in... maybe when multiple modes are requested they are shifted with respect to the 22 mode....

**Comment by llondon6** [comment]
Thanks! Fixed. (not sure why my email responses don't show up here )

**Comment by llondon6** [comment]
Hi Seb. Thanks. This is indeed a bug. I've fixed it on master.

**Comment by Cyberface** [comment]
Cool! We will just have to do any time shift peak adjustment manually. k_max_amp is all the information you need anyway
