### ISSUE TITLE
confing ini files 'catalog_dir' needs to end in slash

### ISSUE THREAD

**Issue by Cyberface** [llondon6/nrutils_dev#19]
In catalogue ini files the filed ' catalog_dir ' is a path such as 

```
catalog_dir = /Users/sebastian/phd/mounts/hogshead_mount/NR_data/ReducedData-hogshead/dirac-nr-followup/
```

If if **doesn't** end in a slash then I think you get an error.

Just a not here for me to fix it later

**Comment by llondon6** [comment]
This should now be fixed.
