### ISSUE TITLE
what does is_extrapolated = 1 do

### ISSUE THREAD

**Issue by Cyberface** [llondon6/nrutils_dev#28]
What does it mean for each code?

for example in silures.ini this is set to 1.

but for my BAM ini file I have this to 0.

what does it do?

**Comment by llondon6** [comment]
Sorry about the lack of clarity here. There isn't consistent commenting about this field.

```python
# IF the waveform data is extrapolated to infinity then
is_extrapolated = 1
# ELSE
is_extrapolated = 0 
```

**Comment by llondon6** [comment]
btw, I don't think that `is_extrapolated` is currently referenced anywhere in nrsc.py, even though it's listed as a required attribute
