### ISSUE TITLE
Label swap issue for edge cases (and possible phase-shift need for BAM)

### ISSUE THREAD

**Issue by thompsonphys** [llondon6/nrutils_dev#47]
https://github.com/llondon6/nrutils_dev/blob/7301aa132eb5ed27f6c0890a9760d1a19a814525/nrutils/handlers/bam.py#L650

I'm not sure how `nrutils` handles the q1a08 cases internally where the BAM data is already swapped, but I could see an issue here with the dynamics if this isn't taken into account later.

**Comment by llondon6** [comment]
Hmm, I don't think it is. Do you think it would suffice to modify the code flow to not swap in the handler for q=1 cases?

**Comment by thompsonphys** [comment]
Should be doable. I use a hacky solution like this
`if not (mass2/mass1 < 1.1 and np.max([np.linalg.norm(X1[0]),np.linalg.norm(X2[0])])>0.70):`
when doing the label swap in the hdf5 script. Since this only affects the q1 cases with high spin, this should step over the swap logic when hitting those cases. But there is undoubtedly a more elegant solution.

**Comment by Cyberface** [comment]
maybe you have to do something to the orbital phase too ? like adding pi?

**Comment by llondon6** [comment]
sounds fair; I'dd pop the logic in the handler at the lines you linked; @Cyberface good point! worth a check

**Comment by llondon6** [comment]
@Cyberface This shift in pi is implicitly accounted for in a few places, but in principle this could be much cleaner by addressing it at this stage.  I've updated the issue title to note this.

**Comment by llondon6** [comment]
@thompsonphys is there anything that needs to be done here?
