### ISSUE TITLE
Inconsistent Spin in dynamics

### ISSUE THREAD

**Issue by thompsonphys** [llondon6/nrutils_dev#48]
https://github.com/llondon6/nrutils_dev/blob/7301aa132eb5ed27f6c0890a9760d1a19a814525/nrutils/core/nrsc.py#L5008

Potential inconsistency in calculating J using the orbital angular momentum and spin information at different times. I couldn't see the spin data being updated in the attributes of the gwylm object prior to J being computed here with the new values of L.

**Comment by llondon6** [comment]
please double check the handler routine -- this should explicitly use the same time for each after interpolation

**Comment by thompsonphys** [comment]
So from what I can tell, the initial metadata is loaded in with `learn_metadata`, where the standard metadata is set to the gwylm attributes (which inclues S1, S2, S) from the initial BAM metadata. When `load_dynamics` is called, these attributes are already set and the `learn_source_dynamics` handler does not update them. This would mean that `y.S` is still pointing the to initial spin of the simulation, not the value stored in `dynamics['S'][0]`. 

On the other hand, the attribute `y.L` was overwritten with `dynamics['L'][0]` just above in this conditional. It's very possible that the spin metadata is also being updated somewhere, but I can't find it.

**Comment by Cyberface** [comment]
would it be possible to not swap things ever? and thus avoid all of this?

**Comment by llondon6** [comment]
I see now - this is in the 'test_quantity<=0' block. This block should not be activated unless the data is inconsistent for some reason. I wrote it to accommodate the q8a08t120 issues that turned out to be a curation mixup. So in theory this code can be removed.

**Comment by thompsonphys** [comment]
> would it be possible to not swap things ever? and thus avoid all of this?
> 
> Or are we way beyond this :)

In principle I like that it _could_ update, since you have the ability to crop the start of the waveform and this could then adjust the stored dynamics metadata to that time (assuming some mapping between waveform and dynamics info). This would then automatically feed into things like `__calc_initial_L_frame_` were we to use the dynamics information for that.

**Comment by llondon6** [comment]
@thompsonphys I agree, and this would not be difficult I think:
1. in the clean routine
2. use the cleaning time to reference the loaded dynamics
3. and store them to the initial parameter fields

**Comment by llondon6** [comment]
@thompsonphys would you be able to have a go at this? and add a print statement to let the user know

**Comment by thompsonphys** [comment]
Yes, I will start looking into that implementation.
