### ISSUE TITLE
Add tortoise coordinate functionality

### ISSUE THREAD

**Issue by thompsonphys** [llondon6/nrutils_dev#49]
https://github.com/llondon6/nrutils_dev/blob/7301aa132eb5ed27f6c0890a9760d1a19a814525/nrutils/core/nrsc.py#L4985

The mapping between the source dynamics time and the waveform time is fixed to be a shift by the extraction radius. I would like to add functionality to choose between either extraction radius or the tortoise coordinate, something like:

```
MADM = this.raw_metadata.initial_ADM_energy
extraction_radius = this.extraction_radius + 2.0 * MADM * np.log(this.extraction_radius / (2.0 * MADM) - 1.0)
```

This could be implemented with the addition of a flag in `load_dynamics`:

```
load_dynamics(this,waveform_times=None,verbose=False,output=False,tortoise=False)
```

**Comment by llondon6** [comment]
please feel free to do this! it definitely sounds useful :)

**Comment by thompsonphys** [comment]
Added with this commit: [624f26c](https://github.com/llondon6/nrutils_dev/tree/624f26c6f913758aebc04c509f926bc49f8a38ba)

Let me know if it's missing something. To use this functionality, the user must first call the `gwylm` object with `load_dynamics=False` and then load the dynamics manually with the flag `tortoise=True`.

**Comment by llondon6** [comment]
this looks good; Would you also be able to add (yet another) option to gwylm such that 'tortiose' could be selected at that level?

**Comment by thompsonphys** [comment]
Yes, maybe something a bit more verbose like `use_tortoise_extraction` or similar?

**Comment by llondon6** [comment]
this would make sense, but may imply that the tortoise coordinate is also being used self-consistently in eg:
* https://github.com/llondon6/nrutils_dev/blob/master/nrutils/core/nrsc.py#L2931-L2937

and related routines ... this shouldn't be that difficult to implement there as well, and should probably by done in the handler's related routine and propigated to gwylm.__r__ and gwylm.r

**Comment by llondon6** [comment]
without making those changes, I'd go with 'use_tortoise_for_dynamics' or 'tortoise_dynamics'

**Comment by thompsonphys** [comment]
Seems like an easy fix to add it to the `BAM` handler here
https://github.com/llondon6/nrutils_dev/blob/624f26c6f913758aebc04c509f926bc49f8a38ba/nrutils/handlers/bam.py#L435
since the requirement of `this` in that code specifically states it must contain the `raw_metadata`, which is all we would need for the ADM mass.

**Comment by thompsonphys** [comment]
And I suppose we would want to convert the `tortoise` flag to an attribute as well if we made this change?

**Comment by llondon6** [comment]
all makes sense to me :) I'd be inclined to add something like `this.r_is_tortoise=True/False` and have this.r() return the tortoise coordinate as calculated in the handler

**Comment by thompsonphys** [comment]
First iteration of this implementation: https://github.com/llondon6/nrutils_dev/commit/95c305834ff068dcb1f38da15925b36b418bd492

Things get a bit complicated because the extraction radius is also used for potential psi4 scaling, which should use the flat coordinate value and not the tortoise coordinate. I'm more than happy to take suggestions about possible improvements on this code!

**Comment by llondon6** [comment]
Thanks @thompsonphys! I'm not sure about the best way to handle r_for_scaling, but am thinking the following as a high-level design:

* NR groups such as BAM scale their data by r perhaps in different ways -- any BAM specific choice should be handled in the "handler"-->bam.py. The result of handling for NR conventions should be r*Psi4 where r is the flat r

* given r*Psi4 the end user should have the choice of calculating r or r* so that they may use either for various things. Importantly r and r* have a bijective map between them, so it should be fine that low-level code uses only one, say r

* this would suggest that it's best to create a low routine that calculates r*, and a few high level routines that allow the user to acres r* and switch between scalings

I think your commit is a great start!

**Comment by llondon6** [comment]
also @thompsonphys are your recent commits compatible with these bits: https://github.com/llondon6/nrutils_dev/blob/master/nrutils/core/nrsc.py#L3040-L3043

that code is almost never executed as most NR groups scale by radius by default, but I will have a think about how to handle it

**Comment by llondon6** [comment]
@thompsonphys do you have an example notebook for how to use your recent changes?

**Comment by thompsonphys** [comment]
This commit (https://github.com/llondon6/nrutils_dev/commit/fdbeb9e79e6277ec0a3b59106c7c0c1482f3e8d3) also fixes a bug with the spin dynamics information where the physical spins were being scaled by the mass.

**Comment by thompsonphys** [comment]
> also @thompsonphys are your recent commits compatible with these bits: https://github.com/llondon6/nrutils_dev/blob/master/nrutils/core/nrsc.py#L3040-L3043
> 
> that code is almost never executed as most NR groups scale by radius by default, but I will have a think about how to handle it

Yes, this bit of code was the initial motivation for the `r_for_scaling` flag: https://github.com/llondon6/nrutils_dev/blob/fdbeb9e79e6277ec0a3b59106c7c0c1482f3e8d3/nrutils/core/nrsc.py#L3050

**Comment by thompsonphys** [comment]
> @thompsonphys do you have an example notebook for how to use your recent changes?

Not yet, but I'll work to have one done probably tomorrow.
