### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by duncanmmacleod** [llondon6/nrutils_dev#59]
@llondon6 what's the state of Python 3 compatibility for this repo? I'm happy to help but see that there's already a `python3_compatibility` branch and don't want to repeat what you've already done.

**Comment by llondon6** [comment]
hi @duncanmmacleod `nrutils3` is technically still in development, but it is in effect at the moment the main development branch (i.e. I am using it for research, and looking for any possible python version issues as I go along)

**Comment by llondon6** [comment]
@duncanmmacleod tangential question: this repo, in principle, needs an install script that's more complex than I can build. There are files that should exist outside of the repo, and be user-specific in content. Currently, every time a Cardiff student or postdoc installs nrutils for the first time, someone has to show them which files to manually change (there at least used to be documentation on this, but alas it is out of date). Is streamlining the installation process with a single install script something you might be able to help with?

**Comment by duncanmmacleod** [comment]
I can certainly offer advice. However, let's not discuss this on this ticket, please open a new ticket and pull me in, or email me.
