### ISSUE TITLE
Name ideas

### ISSUE THREAD

**Issue by Cyberface** [llondon6/nrutils_dev#8]
Did we miss a trick calling it something like

pyNR or NRpy
it doesn't really sound catchy tbh :)
but we could pronounce it pyNER or NERpi haha.

Don't get me wrong, nrutils is good too!

**Comment by llondon6** [comment]
Thanks for starting this thread. It would be great if we could think of a really cool name. I defaulted to nrutils after seeing it used in seemingly independent python toolkits for NR data. Here are a few to add to you list:

nrutils [Default]
nrpy or pynr  (same as yours, but no caps -- for those too lazy to type in caps :-) )
nr (short, but maybe too vague)
nrda (stands for NR Data Analysis)
nral ( NR Analysis Library )
nal ( NR Analysis Library )

`for word in English:
    if word[:2] == 'na' or word[:3] == 'nra':
        if is_the_best(word): # subjective
            package_name = word`

**Comment by Cyberface** [comment]
first of all I like the use of no caps too. far too lazy. agreed.

nr - yeah too short.
nrda - not too bad
nral - not too bad either.
I think my problems with these are that they are difficult to pronounce ahah. It would be nicer to have a name we can say _and_ sounds cool

I'm kind of against pyNR because it sounds like we are doing numerical relativity in python.

I quite like 'nal' actually because it sounds close to LAL - ligo algorithmic library.

maybe pynal or pyNAL (cappa) but it doesn't really make sense unless we have the 'R' in it...
pyNRAL pronounced pi Nural ahaha

**Comment by Cyberface** [comment]
or we could call it CyberPy :p

**Comment by llondon6** [comment]
if we were very official, we could go with "lalnr" ... but I've already imbedded my distaste for lal datatypes into the code, so a direct association with lal may be a stretch

**Comment by llondon6** [comment]
Hi Guys, Are there any strong feelings about changing the name?

**Comment by Cyberface** [comment]
pyNAL?

LALNR - pronounced - lana as in laaaaaana

**Comment by llondon6** [comment]
Hmm, I am still okay with nrutils: it's short and descriptive. Ideas above are good, but they also seem more abstract.

Is it okay if we both propose our favorite, and then let Ed decide?

My favorite is nrutils. It's short and descriptive, without being a pure initialism.

**Comment by Galadirith** [comment]
Hey Guys :D Really sorry I haven't proposed any names of my own.

Here a quick summary of the thoughts on names (mostly just rehashing previous comments)

- **We don't need an embedded `py`** 
There are lots of kl python libraries that don't have `py` or equivalent in the name; `season`, `matplotlib`,  `requests`, `flask` so I don't think we need `py` in the name. I did like `nrpy`, similar to `numpy` but that leads on to ...

- **We don't want to imply numerical relativity** 
Anything with just NR in the name without some sort of descriptive fixation sounds like doing NR directly as Seb already suggested with `pynr`, so we need something more. I did like `nrda` but I agree with Lionel on the initialism issue, almost certainly the name will be better if you expand at least a few of the initials.

- **We don't need/want to imply direct association with LAL**
Kind of echoing Lionels thoughts on LAL datatypes, right now the package has minimal dependency on LAL, so any direct association in the name isn't necessary. In fact that would probably be confusing for anyone using the packages, "Why LAL?"

I'll hold off casting my vote until Seb's chosen his favourite, but thanks to Lionel I now know the difference between an initialism and acronym :D

**Comment by Cyberface** [comment]
> thanks to Lionel I now know the difference between an initialism and acronym :D

And now so do I :)

I agree with all that you say Galadirith.

I think that we will probably end up with nrutils because it's pretty good and says what it does.

I just came up with an almost cool name

data analysis with numerical relativity - DAWN, but it should have an 'R' at the end but it ruins DAWN haha dammit.

numerical relativity post processing - nrpp (don't like it that much or as much as nrutils)

numerical relativity analysis - nranal - lol, just no.

ahhh just remembered the other abbreviation of numerical relativity - num rel , which is nice because it sounds like gen rel :)
Maybe we can do something with that...

numrelpy - pronounced "num-rel-pee" (naah)

numrelysis - numerical relativity analysis - haha.

Look.. it's impossible to come up with anything thats better than 'nrutils' ahah

My vote is for `nrutils'

**Comment by llondon6** [comment]
Hahaha 👍
